import { css } from 'lit'

/**
 * Tailwind stylesheet for Shadow DOM components
 *
 * This exports Tailwind's generated CSS so it can be used in Shadow DOM components.
 * Import this in components that need Tailwind utilities but want to maintain Shadow DOM encapsulation.
 *
 * Usage:
 * ```js
 * import { tailwindStylesheet } from '../styles/tailwind-shadow.js'
 *
 * export class MyComponent extends BaseComponent {
 *   static styles = [tailwindStylesheet, css`...custom styles...`]
 * }
 * ```
 *
 * Note: This is loaded from a separate stylesheet to avoid duplication.
 * In production, consider using a build step to optimize this.
 */

// Fetch the Tailwind stylesheet URL (generated by Vite)
// This will be populated at build time
const tailwindCSSUrl = new URL('../styles/globals.css?inline', import.meta.url)

// For now, we'll export a placeholder. In a real implementation, you'd:
// 1. Use a Vite plugin to extract Tailwind CSS
// 2. Or use a custom build step to generate this file
// 3. Or use unsafeCSS with the actual stylesheet content

export const tailwindStylesheet = css`
  /* Tailwind base styles and utilities for Shadow DOM */
  /* This is a simplified version - in production, use a build step */

  /* Box Model */
  .block {
    display: block;
  }
  .flex {
    display: flex;
  }
  .grid {
    display: grid;
  }
  .hidden {
    display: none;
  }

  /* Flexbox */
  .flex-1 {
    flex: 1 1 0%;
  }
  .items-center {
    align-items: center;
  }
  .justify-center {
    justify-content: center;
  }

  /* Grid */
  .grid-cols-1 {
    grid-template-columns: repeat(1, minmax(0, 1fr));
  }

  /* Spacing */
  .gap-2 {
    gap: 0.5rem;
  }
  .gap-4 {
    gap: 1rem;
  }
  .gap-6 {
    gap: 1.5rem;
  }
  .p-4 {
    padding: 1rem;
  }
  .p-6 {
    padding: 1.5rem;
  }
  .py-4 {
    padding-top: 1rem;
    padding-bottom: 1rem;
  }
  .mb-1 {
    margin-bottom: 0.25rem;
  }
  .mb-2 {
    margin-bottom: 0.5rem;
  }
  .mb-4 {
    margin-bottom: 1rem;
  }
  .mb-8 {
    margin-bottom: 2rem;
  }

  /* Sizing */
  .w-10 {
    width: 2.5rem;
  }
  .h-10 {
    height: 2.5rem;
  }

  /* Typography */
  .text-xs {
    font-size: 0.75rem;
    line-height: 1rem;
  }
  .text-sm {
    font-size: 0.875rem;
    line-height: 1.25rem;
  }
  .text-xl {
    font-size: 1.25rem;
    line-height: 1.75rem;
  }
  .text-3xl {
    font-size: 1.875rem;
    line-height: 2.25rem;
  }
  .font-medium {
    font-weight: 500;
  }
  .font-semibold {
    font-weight: 600;
  }
  .font-bold {
    font-weight: 700;
  }
  .uppercase {
    text-transform: uppercase;
  }
  .tracking-wider {
    letter-spacing: 0.05em;
  }

  /* Colors */
  .text-gray-600 {
    color: rgb(75 85 99);
  }
  .text-gray-900 {
    color: rgb(17 24 39);
  }
  .bg-white {
    background-color: rgb(255 255 255);
  }
  .bg-gray-100 {
    background-color: rgb(243 244 246);
  }

  /* Borders */
  .border-b {
    border-bottom-width: 1px;
  }
  .border-l-4 {
    border-left-width: 4px;
  }
  .border-gray-200 {
    border-color: rgb(229 231 235);
  }
  .border-primary-500 {
    border-color: #8b5cf6;
  }
  .border-success-500 {
    border-color: #10b981;
  }
  .border-warning-500 {
    border-color: #f59e0b;
  }
  .border-danger-500 {
    border-color: #ef4444;
  }
  .rounded-lg {
    border-radius: 0.5rem;
  }
  .rounded-full {
    border-radius: 9999px;
  }

  /* Effects */
  .shadow-card {
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  /* Responsive */
  @media (min-width: 640px) {
    .sm\\:grid-cols-2 {
      grid-template-columns: repeat(2, minmax(0, 1fr));
    }
  }

  @media (min-width: 1024px) {
    .lg\\:grid-cols-4 {
      grid-template-columns: repeat(4, minmax(0, 1fr));
    }
  }
`
